---
ynab:
  access_token: # Your YNAB access token
  budget_id: # the first hash in the url when you open your budget
  cash_account_id:  # if set that it creates transactions
                            # to your cash account if withdrawal is detected
accounts:
  - dumper: :fints
    iban: # iban of your account
    ynab_id: # last hash in the url when you click on the account in YNAB
    username: # online banking username / alias
    password: # online banking PIN (NOT! the pin of your bank card!)
    fints_blz: # Your bank's code / Bankleitzahl
    fints_endpoint: # can be found here: https://www.hbci-zka.de/institute/institut_auswahl.htm
                    # Use the PIN/TAN URL from the link above
  - dumper: :n26
    iban: # n26 iban
    ynab_id: # last hash in the url when you click on the account in YNAB
    username: # n26 username
    password: # n26 password
    set_category: false # default: false, sets the N26 category name as category

  - dumper: :barclaycard
    iban: # Barclaycard iban
    ynab_id: # last hash in the url when you click on the account in YNAB
    username: # Barclaycard username
    password: # Barclaycard password
    product_id: # "Produkt ID" as shown in the table after login